# Layer配置
BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "core"
BBFILE_PATTERN_core = "^${LAYERDIR}/"
BBFILE_PRIORITY_core = "5"

LAYERSERIES_COMPAT_core = "styhead"

# 标记这是核心层
CORE_LAYER = "1"

# 设置PATH环境变量，包含系统工具和工具链路径
PATH := "${PATH}:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:${TOPDIR}/toolchains/aarch64-linux-musleabi_for_x86_64-pc-linux-gnu/bin:${TOPDIR}/toolchains/aarch64-linux-musleabi_for_x86_64-pc-linux-gnu/aarch64-linux-musleabi/bin:${TOPDIR}/toolchains/riscv64-linux-musleabi_for_x86_64-pc-linux-gnu/bin:${TOPDIR}/toolchains/riscv64-linux-musleabi_for_x86_64-pc-linux-gnu/riscv64-linux-musleabi/bin"

# 忽略连接检查
CONNECTIVITY_CHECK_URIS = "" 