# RT-Smart Build Configuration
#
# Machine Selection
MACHINE ??= "qemuarm64"

# Distribution Selection  
DISTRO ?= "smart"

# Build directories
TMPDIR = "${TOPDIR}/tmp"
DL_DIR ?= "${TOPDIR}/downloads"
SSTATE_DIR ?= "${TOPDIR}/sstate-cache"

# Parallelism Options
BB_NUMBER_THREADS ?= "${@oe.utils.cpu_count()}"
PARALLEL_MAKE ?= "-j ${@oe.utils.cpu_count()}"

# Package Management
PACKAGE_CLASSES ?= "package_tar"

# Additional settings
USER_CLASSES ?= "buildstats"
PATCHRESOLVE = "noop"

# QA checks
WARN_QA = "textrel files-invalid incompatible-license xorg-driver-abi buildpaths"
ERROR_QA = "dev-so debug-deps dev-deps debug-files arch pkgconfig la perms useless-rpaths rpaths staticdev ldflags pkgvarcheck already-stripped compile-host-path install-host-path pn-overrides infodir build-deps file-rdeps version-going-backwards host-user-contaminated uppercase-pn patch-fuzz-warning"
