# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "rt-smart"
BBFILE_PATTERN_rt-smart = "^${LAYERDIR}/"
BBFILE_PRIORITY_rt-smart = "10"

# LAYERDEPENDS_meta-rt-smart = "core"
# 移除层依赖以简化构建
LAYERSERIES_COMPAT_rt-smart = "styhead"

PATH := "${PATH}:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:${TOPDIR}/toolchains/aarch64-linux-musleabi_for_x86_64-pc-linux-gnu/bin:${TOPDIR}/toolchains/aarch64-linux-musleabi_for_x86_64-pc-linux-gnu/aarch64-linux-musleabi/bin:${TOPDIR}/toolchains/riscv64-linux-musleabi_for_x86_64-pc-linux-gnu/bin:${TOPDIR}/toolchains/riscv64-linux-musleabi_for_x86_64-pc-linux-gnu/riscv64-linux-musleabi/bin"

# ignore connectivity check
CONNECTIVITY_CHECK_URIS = ""
